---
- name: Install and start Apache
  hosts: all
  become: true # Run task with root privilage

  tasks:
    - name: Update Ubuntu packages
      when: ansible_os_family == 'Debian' # Only execute this task on Debian-based system
      apt:
        update_cache: yes # Update the package cache
        upgrade: dist # Upgrade all packages to the latest version

    - name: Install Apache on Red Hat
      when: ansible_os_family == 'RedHat' # Only execute this task on Red Hat-based system
      package:
        name: httpd # Package name on Red Hat
        state: present # Ensure package is installed

    - name: Install Apache on Ubuntu
      when: ansible_os_family == 'Debian' # Only execute this task on Debian-based system
      package:
        name: apache2 # Package name for Apache on ubuntu
        state: present # Ensure package is installed

    - name: Start Apache service
      service:
        name: "{{'httpd' if ansible_os_family == 'RedHat' else 'apache2' }}" # Service name for Apache
        state: started # Ensure service is running